insert into nativename(cca2,langcode,official,common) values("ZA","afr","Republiek van Suid-Afrika","South Africa");
insert into nativename(cca2,langcode,official,common) values("ZA","eng","Republic of South Africa","South Africa");
insert into nativename(cca2,langcode,official,common) values("ZA","nbl","IRiphabliki yeSewula Afrika","Sewula Afrika");
insert into nativename(cca2,langcode,official,common) values("ZA","nso","Rephaboliki ya Afrika-Borwa ","Afrika-Borwa");
insert into nativename(cca2,langcode,official,common) values("ZA","sot","Rephaboliki ya Afrika Borwa","Afrika Borwa");
insert into nativename(cca2,langcode,official,common) values("ZA","ssw","IRiphabhulikhi yeNingizimu Afrika","Ningizimu Afrika");
insert into nativename(cca2,langcode,official,common) values("ZA","tsn","Rephaboliki ya Aforika Borwa","Aforika Borwa");
insert into nativename(cca2,langcode,official,common) values("ZA","tso","Riphabliki ra Afrika Dzonga","Afrika Dzonga");
insert into nativename(cca2,langcode,official,common) values("ZA","ven","Riphabuḽiki ya Afurika Tshipembe","Afurika Tshipembe");
insert into nativename(cca2,langcode,official,common) values("ZA","xho","IRiphabliki yaseMzantsi Afrika","Mzantsi Afrika");
insert into nativename(cca2,langcode,official,common) values("ZA","zul","IRiphabliki yaseNingizimu Afrika","Ningizimu Afrika");
insert into nativename(cca2,langcode,official,common) values("SJ","nor","Svalbard og Jan Mayen","Svalbard og Jan Mayen");
insert into nativename(cca2,langcode,official,common) values("WS","eng","Independent State of Samoa","Samoa");
insert into nativename(cca2,langcode,official,common) values("WS","smo","Malo Saʻoloto Tutoʻatasi o Sāmoa","Sāmoa");
insert into nativename(cca2,langcode,official,common) values("GM","eng","Republic of the Gambia","Gambia");
insert into nativename(cca2,langcode,official,common) values("KN","eng","Federation of Saint Christopher and Nevis","Saint Kitts and Nevis");
insert into nativename(cca2,langcode,official,common) values("MC","fra","Principauté de Monaco","Monaco");
insert into nativename(cca2,langcode,official,common) values("AW","nld","Aruba","Aruba");
insert into nativename(cca2,langcode,official,common) values("AW","pap","Aruba","Aruba");
insert into nativename(cca2,langcode,official,common) values("GW","por","República da Guiné-Bissau","Guiné-Bissau");
insert into nativename(cca2,langcode,official,common) values("GW","pov","República da Guiné-Bissau","Guiné-Bissau");
insert into nativename(cca2,langcode,official,common) values("KP","kor","조선민주주의인민공화국","조선");
insert into nativename(cca2,langcode,official,common) values("PY","grn","Tetã Paraguái","Paraguái");
insert into nativename(cca2,langcode,official,common) values("PY","spa","República de Paraguay","Paraguay");