insert into capital(cca2,capitalname) values("ZA","Pretoria");
insert into capital(cca2,capitalname) values("ZA","Bloemfontein");
insert into capital(cca2,capitalname) values("ZA","Cape Town");
insert into capital(cca2,capitalname) values("SJ","Longyearbyen");
insert into capital(cca2,capitalname) values("WS","Apia");
insert into capital(cca2,capitalname) values("GM","Banjul");
insert into capital(cca2,capitalname) values("KN","Basseterre");
insert into capital(cca2, capitalname) values("MC","Monaco");
insert into capital(cca2, capitalname) values("AW","Oranjestad");
insert into capital(cca2, capitalname) values("GW","Bissau");
insert into capital(cca2, capitalname) values("KP","Pyongyang");
insert into capital(cca2, capitalname) values("PY","Asunción");