insert into altspellings(cca2,spelling) values("ZA","ZA");
insert into altspellings(cca2,spelling) values("ZA","RSA");
insert into altspellings(cca2,spelling) values("ZA","Suid-Afrika");
insert into altspellings(cca2,spelling) values("ZA","Republic of South Africa");
insert into altspellings(cca2,spelling) values("SJ","SJ");
insert into altspellings(cca2,spelling) values("SJ","Svalbard and Jan Mayen Islands");
insert into altspellings(cca2,spelling) values("WS","WS");
insert into altspellings(cca2,spelling) values("WS","Independent State of Samoa");
insert into altspellings(cca2,spelling) values("WS","Malo Saʻoloto Tutoʻatasi o Sāmoa");
insert into altspellings(cca2,spelling) values("GM","GM");
insert into altspellings(cca2,spelling) values("GM","Republic of the Gambia");
insert into altspellings(cca2,spelling) values("KN","KN");
insert into altspellings(cca2,spelling) values("KN","Federation of Saint Christopher and Nevis");
insert into altspellings(cca2,spelling) values("MC","MC");
insert into altspellings(cca2,spelling) values("MC","Principality of Monaco");
insert into altspellings(cca2,spelling) values("MC","Principauté de Monaco");
insert into altspellings(cca2,spelling) values("AW","AW");
insert into altspellings(cca2,spelling) values("GW","GW");
insert into altspellings(cca2,spelling) values("GW","Republic of Guinea-Bissau");
insert into altspellings(cca2,spelling) values("GW","República da Guiné-Bissau");
insert into altspellings(cca2,spelling) values("KP","KP");
insert into altspellings(cca2,spelling) values("KP","Democratic People's Republic of Korea");
insert into altspellings(cca2,spelling) values("KP","DPRK");
insert into altspellings(cca2,spelling) values("KP","조선민주주의인민공화국");
insert into altspellings(cca2,spelling) values("KP","Chosŏn Minjujuŭi Inmin Konghwaguk");
insert into altspellings(cca2,spelling) values("KP","Korea, Democratic People's Republic of");
insert into altspellings(cca2,spelling) values("KP","북한");
insert into altspellings(cca2,spelling) values("KP","북조선");
insert into altspellings(cca2,spelling) values("PY","PY");
insert into altspellings(cca2,spelling) values("PY","Republic of Paraguay");
insert into altspellings(cca2,spelling) values("PY","República del Paraguay");
insert into altspellings(cca2,spelling) values("PY","Tetã Paraguái");