insert into languages(cca2,langcode,langname) values("ZA","afr","Afrikaans");
insert into languages(cca2,langcode,langname) values("ZA","eng","English");
insert into languages(cca2,langcode,langname) values("ZA","nbl","Southern Ndebele");
insert into languages(cca2,langcode,langname) values("ZA","nso","Northern Sotho");
insert into languages(cca2,langcode,langname) values("ZA","sot","Southern Sotho");
insert into languages(cca2,langcode,langname) values("ZA","ssw","Swazi");
insert into languages(cca2,langcode,langname) values("ZA","tsn","Tswana");
insert into languages(cca2,langcode,langname) values("ZA","tso","Tsonga");
insert into languages(cca2,langcode,langname) values("ZA","ven","Venda");
insert into languages(cca2,langcode,langname) values("ZA","xho","Xhosa");
insert into languages(cca2,langcode,langname) values("ZA","zul","Zulu");
insert into languages(cca2,langcode,langname) values("SJ","nor","Norwegian");
insert into languages(cca2,langcode,langname) values("WS","eng","English");
insert into languages(cca2,langcode,langname) values("WS","smo","Samoan");
insert into languages(cca2,langcode,langname) values("GM","eng","English");
insert into languages(cca2,langcode,langname) values("KN","eng","English");
insert into languages(cca2,langcode,langname) values("MC","fra","French");
insert into languages(cca2,langcode,langname) values("AW","nld","Dutch");
insert into languages(cca2,langcode,langname) values("AW","pap","Papiamento");
insert into languages(cca2,langcode,langname) values("GW","por","Portuguese");
insert into languages(cca2,langcode,langname) values("GW","pov","Upper Guinea Creole");
insert into languages(cca2,langcode,langname) values("KP","kor","Korean");
insert into languages(cca2,langcode,langname) values("PY","grn","Guaraní");
insert into languages(cca2,langcode,langname) values("PY","spa","Spanish");
