insert into demonyms(cca2,code,f,m) values("ZA","eng","South African","South African");
insert into demonyms(cca2,code,f,m) values("ZA","fra","Sud-africaine","Sud-africain");
insert into demonyms(cca2,code,f,m) values("SJ","eng","Norwegian","Norwegian");
insert into demonyms(cca2,code,f,m) values("WS","eng","Samoan","Samoan");
insert into demonyms(cca2,code,f,m) values("WS","fra","Samoane","Samoan");
insert into demonyms(cca2,code,f,m) values("GM","eng","Gambian","Gambian");
insert into demonyms(cca2,code,f,m) values("GM","fra","Gambienne","Gambien");
insert into demonyms(cca2,code,f,m) values("KN","eng","Kittitian or Nevisian","Kittitian or Nevisian");
insert into demonyms(cca2,code,f,m) values("KN","fra","Kittitienne-et-nevicienne","Kittitien-et-nevicien");
insert into demonyms(cca2,code,f,m) values("MC","eng","Monegasque","Monegasque");
insert into demonyms(cca2,code,f,m) values("MC","fra","Monégasque","Monégasque");
insert into demonyms(cca2,code,f,m) values("AW","eng","Aruban","Aruban");
insert into demonyms(cca2,code,f,m) values("AW","fra","Arubaise","Arubais");
insert into demonyms(cca2,code,f,m) values("GW","eng","Guinea-Bissauan","Guinea-Bissauan");
insert into demonyms(cca2,code,f,m) values("GW","fra","Bissau-Guinéenne","Bissau-Guinéen");
insert into demonyms(cca2,code,f,m) values("KP","eng","North Korean","North Korean");
insert into demonyms(cca2,code,f,m) values("KP","fra","Nord-coréenne","Nord-coréen");
insert into demonyms(cca2,code,f,m) values("PY","eng","Paraguayan","Paraguayan");
insert into demonyms(cca2,code,f,m) values("PY","fra","Paraguayenne","Paraguayen");
