insert into car_signs(cca2,sign) values("ZA","ZA");
insert into car_signs(cca2,sign) values("SJ","N");
insert into car_signs(cca2,sign) values("WS","WS");
insert into car_signs(cca2,sign) values("GM","WAG");
insert into car_signs(cca2,sign) values("KN","KN");
insert into car_signs(cca2,sign) values("MC","MC");
insert into car_signs(cca2,sign) values("GW","RGB");
insert into car_signs(cca2,sign) values("KP","");
insert into car_signs(cca2,sign) values("PY","PY");